import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <Link href="/csr">
            <a className={styles.card}>
              <h2>CSR &rarr;</h2>
              <p>CSR Example</p>
            </a>
          </Link>

          <Link href="/ssr">
            <a className={styles.card}>
              <h2>SSR &rarr;</h2>
              <p>SSR Example</p>
            </a>
          </Link>

          <Link href="/ssg">
            <a className={styles.card}>
              <h2>SSG &rarr;</h2>
              <p>SSG Example</p>
            </a>
          </Link>

          <Link href="/isr">
            <a className={styles.card}>
              <h2>ISR &rarr;</h2>
              <p>ISR Example</p>
            </a>
          </Link>

          <Link href="/users">
            <a className={styles.card}>
              <h2>getStaticPaths &rarr;</h2>
              <p>getStaticPaths Example</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
